// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(loggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"landing\"><section class=\"hero\"><div class=\"hero-content\"><div class=\"hero-badge\">Open Source</div><h1 class=\"hero-title\"><span class=\"hero-accent\">Open</span>Discord</h1><p class=\"hero-subtitle\">Explore your Discord servers like never before.<br>Search messages, analyze activity, track members — all in a beautiful dark UI.</p><div class=\"hero-actions\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if loggedIn {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/app/guilds\" class=\"btn-primary\">Open Dashboard</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/auth/login\" class=\"btn-primary\">Login with Discord</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"https://github.com/steipete/discrawl\" class=\"btn-secondary\" target=\"_blank\" rel=\"noopener\">View on GitHub</a></div></div></section><section class=\"features\"><div class=\"features-grid\"><div class=\"feature-card\"><div class=\"feature-icon\">💬</div><h3>Message Browser</h3><p>Browse channel messages with Discord-like UI. Newest-first, infinite scroll, jump-to-message links.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🔍</div><h3>Full-Text Search</h3><p>FTS5-powered search across all messages. Find anything in seconds with highlighted results.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">📊</div><h3>Analytics Dashboard</h3><p>Message volume, activity heatmaps, top members, channel stats — with interactive charts.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">⚡</div><h3>Live Updates</h3><p>Server-Sent Events stream new messages in real-time. Keyword alerts notify you instantly.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">👥</div><h3>Member Profiles</h3><p>View member activity, roles, and message history. Track community engagement at a glance.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🔒</div><h3>Secure by Design</h3><p>Discord OAuth2 login, encrypted token storage, per-user rate limiting, NSFW content gates.</p></div></div></section><section class=\"tech-section\"><h2>Built Different</h2><p class=\"tech-subtitle\">Single binary. No Node.js. No Docker. Just run it.</p><div class=\"tech-pills\"><span class=\"tech-pill\">Go</span> <span class=\"tech-pill\">SQLite</span> <span class=\"tech-pill\">HTMX</span> <span class=\"tech-pill\">SSE</span> <span class=\"tech-pill\">Chart.js</span> <span class=\"tech-pill\">Zero JS Build Step</span></div></section><footer class=\"landing-footer\"><p>OpenDiscord — Discord Server Visualizer</p></footer></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("OpenDiscord").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
