version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - govet
    - intrange
    - ineffassign
    - misspell
    - modernize
    - nilerr
    - nilnesserr
    - nolintlint
    - perfsprint
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign

formatters:
  enable:
    - gofumpt
    - goimports
