version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - nilerr
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - wastedassign

formatters:
  enable:
    - gofumpt
    - goimports
