// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package analytics

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/steipete/discrawl/internal/web/templates/layout"
)

func Dashboard(guildID string, guildName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"analytics-page\"><div class=\"analytics-header\"><h2>Analytics</h2><div class=\"analytics-controls\"><label for=\"days-filter\">Period:</label> <select id=\"days-filter\" onchange=\"refreshCharts()\"><option value=\"7\">Last 7 days</option> <option value=\"30\" selected>Last 30 days</option> <option value=\"90\">Last 90 days</option></select> <button id=\"custom-range-toggle\" type=\"button\" onclick=\"toggleCustomRange()\">Custom Range</button></div></div><div id=\"custom-range-picker\" class=\"custom-range-picker\" style=\"display:none;\"><label for=\"date-from\">From:</label> <input type=\"date\" id=\"date-from\" name=\"date-from\"> <label for=\"date-to\">To:</label> <input type=\"date\" id=\"date-to\" name=\"date-to\"> <button type=\"button\" onclick=\"applyCustomRange()\">Apply</button></div><input type=\"hidden\" id=\"guild-id\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(guildID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/analytics/dashboard.templ`, Line: 29, Col: 53}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div id=\"overview-cards\" class=\"overview-cards\"></div><div class=\"analytics-grid\"><div class=\"chart-card chart-card--wide\"><h3 class=\"chart-title\">Message Volume</h3><canvas id=\"msg-volume\"></canvas></div><div class=\"chart-card chart-card--wide\"><h3 class=\"chart-title\">Activity Heatmap</h3><canvas id=\"activity-heatmap\"></canvas></div><div class=\"chart-card\"><h3 class=\"chart-title\">Top Members</h3><canvas id=\"top-members\"></canvas></div><div class=\"chart-card\"><h3 class=\"chart-title\">Channel Activity</h3><canvas id=\"channel-activity\"></canvas></div></div></div><script src=\"https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js\"></script> <script src=\"/static/js/analytics.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.AppShell("Analytics", guildID, guildName).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
